#!/system/bin/sh
# ni sh buat ganti mode paling cepet di dunia AWKWKWKWK
echo 'preparing . . .'
if [ "$(id -u)" -gt "0" ] && [ "$(whoami)" != "root" ]; then
    echo $merahHitam"please type 'su' first -_-"$ResetWarna
    echo ""
    echo "Exit after :"
    for timeExit in "3s 2s 1s 0s" ;
    do
        echo "$timeExit"
        usleep 1000000
    done
    exit -1
fi
GetBusyBox="none"
PathBusyBox="none"
for i in /system/bin /system/xbin /sbin /su/xbin; do
    if [ "$GetBusyBox" == "none" ]; then
        if [ -f $i/busybox ]; then
            GetBusyBox=$i/busybox;
        fi;
        PathBusyBox=$i
    fi;
done;
usleep=usleep
if [ -e "$PathBusyBox/usleep" ];then
    usleep=$PathBusyBox/usleep
fi
nohup=nohup
if [ -e "$PathBusyBox/nohup" ];then
    nohup=$PathBusyBox/nohup
fi
ModulPath=$(cat /system/etc/ZyC_Ai/magisk_path.txt)
if [ ! -e $ModulPath/ZyC_Turbo/system/etc/ZyC_Ai/mod_path.txt ]; then
    zyc_turbo
fi
ModPath=$(cat $ModulPath/ZyC_Turbo/system/etc/ZyC_Ai/mod_path.txt)
Path=$ModPath/modul_mantul/ZyC_mod
PathModulConfigAi=$Path/ZyC_Ai
if [ ! -e "/system/etc/ZyC_Ai" ];then
    echo "ai not found"
    exit -1;
fi
if [ ! -z "$1" ];then
    if [ "$1" == "on" ];then
        echo "updating auto mode to '1',please wait. . .";
        echo "1" > $PathModulConfigAi/ai_status.txt;
        $usleep 100000
        echo "update auto mode to '1' done .";
        
    elif [ "$1" == "off" ];then
        echo "updating auto mode to '3',please wait. . .";
        echo "3" > $PathModulConfigAi/ai_status.txt;
        $usleep 100000
        echo "update auto mode to '3' done .";
    else
        echo "updating auto mode to '$1',please wait. . .";
        echo "$1" > $PathModulConfigAi/ai_status.txt;
        $usleep 100000
        echo "update auto mode to '$1' done .";
    fi
fi;
if [ -e "$PathModulConfigAi/ai_status.txt" ];then
    aiStatus=$(cat "$PathModulConfigAi/ai_status.txt");
    if [ "$aiStatus" == '0' ];then
        echo "set ai status to 1 first"  
    elif [ "$aiStatus" == '3' ];then
        echo "check log,auto mode turned off,if not wait a minutes xD"
    elif [ "$aiStatus" == '2' ];then
        echo "ai mode still running"
    else
        $nohup ./system/etc/ZyC_Ai/ai_mode.sh 2>/dev/null 1>/dev/null& 
        echo "close this terminal, the ai mode has been running"
    fi
else
    $nohup ./system/etc/ZyC_Ai/ai_mode.sh 2>/dev/null 1>/dev/null& 
    echo "close this terminal, the ai mode has been running"
fi