#!/system/bin/sh
# ni sh buat ganti mode lah
echo 'wait . . .';
if [ "$(id -u)" -gt "0" ] && [ "$(whoami)" != "root" ]; then
    echo $merahHitam"please type 'su' first -_-"$ResetWarna
    echo ""
    echo "Exit after :"
    for timeExit in "3s 2s 1s 0s" ;
    do
        echo "$timeExit"
        usleep 1000000
    done
    exit -1
fi
if [ ! -e /data/mod_path.txt ]; then
    zyc_turbo
fi
ModPath=$(cat /data/mod_path.txt)
Path=$ModPath/modul_mantul/ZyC_mod
PathModulConfig=$Path/ZyC_Turbo_config
mode=$(cat "$PathModulConfig/status_modul.txt")
echo "you use mode [$mode]"
echo "Change mode script to? : ";
read  modeNya
if [ -z $modeNya ];then
    echo "you still use [$mode]";
else
    echo $modeNya > $PathModulConfig/status_modul.txt;
    echo "mode updated to [$modeNya]";
    zyc_turbo > /dev/null 2>&1
fi;
echo 'request done . . .';
echo "see log at $Path/ZyC_turbo.log";
