#!/system/bin/sh
# ni sh buat ganti mode lah
echo 'wait . . .';
echo "Change render mode script to? : ";
render=$(cat "/data/media/0/modul_mantul/ZyC_mod/ZyC_Turbo_config/mode_render.txt");
echo "you use render mode [$render]";
read  modeNya
if [ -z $modeNya ];then
    echo "you still use [$render]";
else
    echo $modeNya > /data/media/0/modul_mantul/ZyC_mod/ZyC_Turbo_config/mode_render.txt;
    echo "mode updated to [$modeNya]";
fi;
echo 'request done . . .';
