#!/system/bin/sh
# ni sh buat ganti mode paling cepet di dunia AWKWKWKWK
echo 'preparing . . .'
GetBusyBox="none"
PathBusyBox="none"
for i in /system/bin /system/xbin /sbin /su/xbin; do
    if [ "$GetBusyBox" == "none" ]; then
        if [ -f $i/busybox ]; then
            GetBusyBox=$i/busybox
        fi
        PathBusyBox=$i
    fi
done
usleep=usleep
if [ -e "$PathBusyBox/busybox" ]; then
    usleep=$PathBusyBox"/busybox usleep"
fi
nohup=nohup
if [ -e "$PathBusyBox/busybox" ]; then
    nohup=$PathBusyBox"/busybox nohup"
fi
if [ "$(id -u)" -gt "0" ] && [ "$(whoami)" != "root" ]; then
    echo $merahHitam"please type 'su' first -_-"$ResetWarna
    echo ""
    echo "Exit after :"
    for timeExit in "3s 2s 1s 0s" ;
    do
        echo "$timeExit"
        $usleep 1000000
    done
    exit -1
fi
ModulPath=$(cat /system/etc/ZyC_Ai/magisk_path.txt)
if [ ! -e $ModulPath/ZyC_Turbo/system/etc/ZyC_Ai/mod_path.txt ]; then
    zyc_turbo
fi
ModPath=$(cat $ModulPath/ZyC_Turbo/system/etc/ZyC_Ai/mod_path.txt)
Path=$ModPath/modul_mantul/ZyC_mod
PathModulConfig=$Path/ZyC_Turbo_config
if [ ! -z "$1" ]; then
    echo "updating mode to '$1',please wait. . ."
    printf "$1" | zyc_mode 2>/dev/null 1>/dev/null
    $usleep 100000
    echo "update mode to '$1' done ."
fi
if [ ! -z "$2" ]; then
    echo "updating mode render to '$2',please wait. . ."
    printf "$2" | zyc_render 2>/dev/null 1>/dev/null
    $usleep 100000
    echo "update mode render to '$2' done ."
fi
zyc_turbo 2>/dev/null 1>/dev/null
mode=$(cat "$PathModulConfig/status_modul.txt")
render=$(cat "$PathModulConfig/mode_render.txt")
echo "use mode [$mode]  and render using [$render]"
echo 'request done . . .'
echo "see log at $Path/ZyC_turbo.log"
