#!/system/bin/sh
# ni sh buat nge trigger ganti mode aja
echo 'wait . . .';
if [ "$(id -u)" -gt "0" ] && [ "$(whoami)" != "root" ]; then
    echo $merahHitam"please type 'su' first -_-"$ResetWarna
    echo ""
    echo "Exit after :"
    for timeExit in "3s 2s 1s 0s" ;
    do
        echo "$timeExit"
        usleep 1000000
    done
    exit -1
fi
magisk=$(ls /data/adb/magisk/magisk || ls /sbin/magisk) 2>/dev/null;
GetVersion=$($magisk -c | grep -Eo '[0-9]{2}\.[0-9]+')
case "$GetVersion" in
'15.'[1-9]*) # Version 15.1 - 15.9
	ModulPath=/sbin/.core/img
;;
'16.'[1-9]*) # Version 16.1 - 16.9
	ModulPath=/sbin/.core/img
;;
'17.'[1-3]*) # Version 17.1 - 17.3
	ModulPath=/sbin/.core/img
;;
'17.'[4-9]*) # Version 17.4 - 17.9
	ModulPath=/sbin/.magisk/img
;;
'18.'[0-9]*) # Version 18.x
	ModulPath=/sbin/.magisk/img
;;
'19.'[0-9a-zA-Z]*) # Version 19.x
	ModulPath=/data/adb/modules
;;
'20.'[0-9a-zA-Z]*) # Version 20.x
	ModulPath=/data/adb/modules
;;
*)
    echo "unsupported magisk version detected,fail"
    exit -1;
;;
esac
sh $ModulPath/ZyC_Turbo/initialize.sh "terminal" & wait
RunStatus="kaga"
if [ ! -e /data/mod_path.txt ]; then
    nohup sh $ModulPath/ZyC_Turbo/service.sh "Terminal" & 
	RunStatus="iya"
fi
ModPath=$(cat /data/mod_path.txt)
Path=$ModPath/modul_mantul/ZyC_mod
PathModulConfig=$Path/ZyC_Turbo_config
if [ $RunStatus == "kaga" ];then
	nohup sh $ModulPath/ZyC_Turbo/service.sh "Terminal" & 
fi
mode=$(cat "$PathModulConfig/status_modul.txt");
render=$(cat "$PathModulConfig/mode_render.txt");
echo "use mode [$mode]  and render using [$render]";
echo "see log at $Path/ZyC_turbo.log";
echo 'request done . . .';
