#!/system/bin/sh
# ni sh buat nge trigger ganti mode aja
# setting warna
abuHitam='\e[01;90m' > /dev/null 2>&1; # abu abu - hitam
putihHitam='\e[01;40m' > /dev/null 2>&1; # putih - hitam
merahHitam='\e[01;91m' > /dev/null 2>&1; # merah - hitam
merahPutih='\e[01;41m' > /dev/null 2>&1; # merah - putih
kuningHitam='\e[01;93m' > /dev/null 2>&1; # kuning - hitam
kuningPutih='\e[01;43m' > /dev/null 2>&1; # kuning - putih
biruHitam='\e[01;94m' > /dev/null 2>&1; # biru - hitam
biruPutih='\e[01;104m' > /dev/null 2>&1; # biru - putih
cyanHitam='\e[01;96m' > /dev/null 2>&1; # cyan - hitam
cyanPutih='\e[01;46m' > /dev/null 2>&1; # cyan - putih
hijauHitam='\e[01;92m' > /dev/null 2>&1; # hijau - hitam
hijauPutih='\e[01;42m' > /dev/null 2>&1; # hijau - putih
unguHitam='\e[01;95m' > /dev/null 2>&1; # ungu - hitam
unguPutih='\e[01;45m' > /dev/null 2>&1; # ungu - putih
ResetWarna='\e[0m' > /dev/null 2>&1; # Buat Reser Warna
# setting warna end
echo $kuningPutih"Preparing Config . . . ."$ResetWarna
sleep 5s
magisk=$(ls /data/adb/magisk/magisk || ls /sbin/magisk) 2>/dev/null;
GetVersion=$($magisk -c | grep -Eo '[1-9]{2}\.[0-9]+')
case "$GetVersion" in
'15.'[1-9]*) # Version 15.1 - 15.9
	ModulPath=/sbin/.core/img
;;
'16.'[1-9]*) # Version 16.1 - 16.9
	ModulPath=/sbin/.core/img
;;
'17.'[1-3]*) # Version 17.1 - 17.3
	ModulPath=/sbin/.core/img
;;
'17.'[4-9]*) # Version 17.4 - 17.9
	ModulPath=/sbin/.magisk/img
;;
'18.'[0-9]*) # Version 18.x
	ModulPath=/sbin/.magisk/img
;;
'19.'[0-9a-zA-Z]*) # Version 19.x
	ModulPath=/data/adb/modules
;;
*)
    echo "unsupported magisk version detected,fail"
    exit -1;
;;
esac
if [ ! -e /data/mod_path.txt ]; then
    zyc_turbo
fi
ModPath=$(cat /data/mod_path.txt)
Path=$ModPath/modul_mantul/ZyC_mod
PathModulConfig=$Path/ZyC_Turbo_config
PathModulConfigAi=$Path/ZyC_Ai
Perubahan="tidak"
if [ -e $PathModulConfig/status_modul.txt ];then
    GetModeBefore=$(cat "$PathModulConfig/status_modul.txt")
    GetModeNew=$(cat "$PathModulConfig/status_modul.txt")
fi
if [ -e $PathModulConfig/mode_render.txt ];then
    GetModeRenderBefore=$(cat "$PathModulConfig/mode_render.txt")
    GetModeRenderNew=$(cat "$PathModulConfig/mode_render.txt")
fi
if [ -e $PathModulConfig/fastcharge.txt ];then
    GetModeFCBefore=$(cat "$PathModulConfig/fastcharge.txt")
    GetModeFCNew=$(cat "$PathModulConfig/fastcharge.txt")
fi
if [ -e $PathModulConfig/fsync_mode.txt ];then
    GetModeFsyncBefore=$(cat "$PathModulConfig/fsync_mode.txt")
    GetModeFsyncNew=$(cat "$PathModulConfig/fsync_mode.txt")
fi
if [ -e $PathModulConfig/GpuBooster.txt ];then
    GetModeAdrenoBefore=$(cat "$PathModulConfig/GpuBooster.txt")
    GetModeAdrenoNew=$(cat "$PathModulConfig/GpuBooster.txt")
fi
if [ -e $PathModulConfig/custom_ram_management.txt ];then
    GetModeRamBefore=$(cat "$PathModulConfig/custom_ram_management.txt")
    GetModeRamNew=$(cat "$PathModulConfig/custom_ram_management.txt")
fi
if [ -e $PathModulConfigAi/ai_status.txt ];then
    GetModeAiBefore=$(cat "$PathModulConfigAi/ai_status.txt")
    GetModeAiNew=$(cat "$PathModulConfigAi/ai_status.txt")
fi
savedata="no"
ListMenu(){
    clear
    echo "list menu : "
    if [ -e "$PathModulConfig/status_modul.txt" ];then
        echo "mx > turn off tweak";
        echo "my > change mode tweak to on"
        echo "mt > change mode tweak to turbo"
        if [ "$GetModeBefore" != "$GetModeNew" ];then
            echo $kuningHitam"this will set to : $GetModeNew"$ResetWarna
        else
            echo "current status : $GetModeBefore";
        fi
        echo $cyanPutih"<--- ---- --- --->"$ResetWarna
    fi
    if [ -e "$PathModulConfig/mode_render.txt" ];then
        
        echo "opd > Use Default OpenGL render"
        echo "ops > Use OpenGL Skia render"
        echo "vkn > Use Vulkan render"
        if [ "$GetModeRenderBefore" != "$GetModeRenderNew" ];then
            if [ $GetModeRenderNew == "opengl" ];then
                echo $hijauHitam"this will set to : OpenGL Default"$ResetWarna
            elif [ $GetModeRenderNew == "skiagl" ];then
                echo $kuningHitam"this will set to : OpenGL Skia"$ResetWarna
            elif [ $GetModeRenderNew == "skiavk" ];then
                echo $merahHitam"this will set to : Vulkan"$ResetWarna
            fi
        else
            if [ $GetModeRenderBefore == "opengl" ];then
                echo $hijauHitam"Current Status : OpenGL Default"$ResetWarna
            elif [ $GetModeRenderBefore == "skiagl" ];then
                echo $kuningHitam"Current Status : OpenGL Skia"$ResetWarna
            elif [ $GetModeRenderBefore == "skiavk" ];then
                echo $merahHitam"Current Status : Vulkan"$ResetWarna
            fi
        fi
        echo $cyanPutih"<--- ---- --- --->"$ResetWarna
    fi
    if [ -e "$PathModulConfig/fastcharge.txt" ];then
        echo "fx > fastcharge option by system"
        echo "fy > fastcharge option by this tweak"
        if [ "$GetModeFCBefore" != "$GetModeFCNew" ];then
            if [ $GetModeFCNew == "0" ];then
                echo $hijauHitam"this will set to : by system"$ResetWarna
            elif [ $GetModeFCNew == "1" ];then
                echo $hijauHitam"this will set to : by this tweak(trying to force on)"$ResetWarna
            fi
        else
            if [ $GetModeFCBefore == "0" ];then
                echo $hijauHitam"Current Status : by system"$ResetWarna
            elif [ $GetModeFCBefore == "1" ];then
                echo $hijauHitam"Current Status : by this tweak(trying to force on)"$ResetWarna
            fi
        fi
        echo $cyanPutih"<--- ---- --- --->"$ResetWarna
    fi
    if [ -e "$PathModulConfig/fsync_mode.txt" ];then
        echo "fcx > turn off fsync"
        echo "fcy > turn on fsync"
        if [ "$GetModeFsyncBefore" != "$GetModeFsyncNew" ];then
            if [ $GetModeFsyncNew == "0" ];then
                echo $hijauHitam"this will set to : off"$ResetWarna
            elif [ $GetModeFsyncNew == "1" ];then
                echo $merahHitam"this will set to : on"$ResetWarna
            fi
        else
            if [ $GetModeFsyncBefore == "0" ];then
                echo $hijauHitam"Current Status : off"$ResetWarna
            elif [ $GetModeFsyncBefore == "1" ];then
                echo $merahHitam"Current Status : on"$ResetWarna
            fi
        fi
        echo $cyanPutih"<--- ---- --- --->"$ResetWarna
    fi
    if [ -e "$PathModulConfig/GpuBooster.txt" ];then
        echo "adx > turn off adrenoboost"
        echo "adl > set adreno boost to low"
        echo "adm > set adreno boost to med"
        echo "adh > set adreno boost to high"
        echo "adt > set adreno boost by tweak"
        if [ "$GetModeAdrenoBefore" != "$GetModeAdrenoNew" ];then
           if [ $GetModeAdrenoNew == "0" ];then
                echo $hijauHitam"this will set to : off"$ResetWarna
            elif [ $GetModeAdrenoNew == "1" ];then
                echo $hijauHitam"this will set to : low"$ResetWarna
            elif [ $GetModeAdrenoNew == "2" ];then
                echo $kuningHitam"this will set to : medium"$ResetWarna
            elif [ $GetModeAdrenoNew == "3" ];then
                echo $kuningHitam"this will set to : high"$ResetWarna
            elif [ $GetModeAdrenoNew == "4" ];then
                echo $biruHitam"this will set to : by tweak"$ResetWarna
            fi
        else
            if [ $GetModeAdrenoBefore == "0" ];then
                echo $hijauHitam"Current status : off"$ResetWarna
            elif [ $GetModeAdrenoBefore == "1" ];then
                echo $hijauHitam"Current status : low"$ResetWarna
            elif [ $GetModeAdrenoBefore == "2" ];then
                echo $kuningHitam"Current status : medium"$ResetWarna
            elif [ $GetModeAdrenoBefore == "3" ];then
                echo $kuningHitam"Current status : high"$ResetWarna
            elif [ $GetModeAdrenoBefore == "4" ];then
                echo $biruHitam"Current status : by tweak"$ResetWarna
            fi
        fi
        echo $cyanPutih"<--- ---- --- --->"$ResetWarna
    fi
    if [ -e "$PathModulConfig/custom_ram_management.txt" ];then
        echo "rms > use system ram management"
        echo "rm1 > use ram management method 1"
        echo "rm2 > use ram management method 2"
        echo "rm3 > use ram management method 3"
        if [ "$GetModeRamBefore" != "$GetModeRamNew" ];then
            if [ $GetModeRamNew == "0" ];then
                echo $hijauHitam"this will set to : use system "$ResetWarna
            else 
                echo $merahHitam"this will set to : method $GetModeRamNew"$ResetWarna
            fi
        else
            if [ $GetModeRamNew == "0" ];then
                echo $hijauHitam"current status : use system "$ResetWarna
            else 
                echo $merahHitam"current status : method $GetModeRamNew"$ResetWarna
            fi
        fi
        echo $cyanPutih"<--- ---- --- --->"$ResetWarna
    fi
    if [ -e "$PathModulConfigAi/ai_status.txt" ];then
        echo "aix > auto/ai mode off"
        echo "aiy > auto/ai mode on"
        if [ "$GetModeAiBefore" != "$GetModeAiNew" ];then
            if [ $GetModeAiNew == "0" ];then
                echo $cyanHitam"this will set to : off"$ResetWarna
            elif [ $GetModeAiNew == "3" ];then
                echo $cyanHitam"this will set to : turn off"$ResetWarna
            elif [ $GetModeAiNew == "1" ];then
                echo $cyanHitam"this will set to : on"$ResetWarna
            fi
        else
            if [ $GetModeAiBefore == "0" ];then
                echo $cyanHitam"current status : off"$ResetWarna
            elif [ $GetModeAiBefore == "2" ];then
                echo $cyanHitam"current status : running"$ResetWarna
            elif [ $GetModeAiBefore == "1" ];then
                echo $cyanHitam"current status : on"$ResetWarna
            fi
        fi
        echo $cyanPutih"<--- ---- --- --->"$ResetWarna
    fi
    echo "more setting coming soon :p"
    if [ $Perubahan == "ya" ];then
        echo "s/save > save setting"
        # echo "0 > exit"
    fi
    echo "0 > exit"
    read pilihan
    if [ $pilihan == "mx" ];then
        Perubahan="ya"
        GetModeNew="off"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "my" ];then
        Perubahan="ya"
        GetModeNew="on"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "mt" ];then
        Perubahan="ya"
        GetModeNew="turbo"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "opd" ];then
        Perubahan="ya"
        GetModeRenderNew="opengl"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "ops" ];then
        Perubahan="ya"
        GetModeRenderNew="skiagl"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "vkn" ];then
        Perubahan="ya"
        GetModeRenderNew="skiavk"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "fx" ];then
        Perubahan="ya"
        GetModeFCNew="0"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "fy" ];then
        Perubahan="ya"
        GetModeFCNew="1"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "fcx" ];then
        Perubahan="ya"
        GetModeFsyncNew="0"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "fcy" ];then
        Perubahan="ya"
        GetModeFsyncNew="1"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "adx" ];then
        Perubahan="ya"
        GetModeAdrenoNew="0"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "adl" ];then
        Perubahan="ya"
        GetModeAdrenoNew="1"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "adm" ];then
        Perubahan="ya"
        GetModeAdrenoNew="2"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "adh" ];then
        Perubahan="ya"
        GetModeAdrenoNew="3"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "adt" ];then
        Perubahan="ya"
        GetModeAdrenoNew="4"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "rms" ];then
        Perubahan="ya"
        GetModeRamNew="0"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "rm1" ];then
        Perubahan="ya"
        GetModeRamNew="1"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "rm2" ];then
        Perubahan="ya"
        GetModeRamNew="2"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "rm3" ];then
        Perubahan="ya"
        GetModeRamNew="3"
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "aix" ];then
        Perubahan="ya"
        # GetModeAiNew="1"
        if [ $GetModeAiBefore == "2" ];then
            GetModeAiNew="3"
        else
            GetModeAiNew="0"
        fi
        sleep 0.1s
        ListMenu
    elif [ $pilihan == "aiy" ];then
        Perubahan="ya"
        if [ $GetModeAiBefore == "0" ];then
            GetModeAiNew="1"
        else
            echo "ai still running . . ."
            GetModeAiNew="2"
            sleep 2s
        fi
        sleep 0.1s
        ListMenu
        
    elif [ $pilihan == "0" ];then
        exitSetting
    else 
        if [ $Perubahan == "ya" ];then
            if [ $pilihan == "s" ];then
                savedata="yes"
            elif [ $pilihan == "save" ];then
                savedata="yes"
            else
                savedata="no"
            fi
            if [ $savedata == "yes" ];then
                saveSetting
            fi
        fi
        echo "request not found,please try again"
        sleep 1s
        sleep 0.1s
        ListMenu
    fi
}
exitSetting(){
    echo "selamat tinggal :v "
    echo "Exit . . . "
    exit -1;
}
saveSetting()
{
    echo "saving changes . . ."
    if [ "$GetModeBefore" != "$GetModeNew" ];then
        echo "$GetModeNew" > $PathModulConfig/status_modul.txt ; 
        GetModeBefore=$GetModeNew;
    fi
    if [ "$GetModeRenderBefore" != "$GetModeRenderNew" ];then
        echo "$GetModeRenderNew" > $PathModulConfig/mode_render.txt ; 
        GetModeRenderBefore=$GetModeRenderNew;
    fi
    if [ "$GetModeFCBefore" != "$GetModeFCNew" ];then
        echo "$GetModeFCNew" > $PathModulConfig/fastcharge.txt ; 
        GetModeFCBefore=$GetModeFCNew;
    fi
    if [ "$GetModeFsyncBefore" != "$GetModeFsyncNew" ];then
        echo "$GetModeFsyncNew" > $PathModulConfig/fsync_mode.txt ; 
        GetModeFsyncBefore=$GetModeFsyncNew;
    fi
    if [ "$GetModeAdrenoBefore" != "$GetModeAdrenoNew" ];then
        echo "$GetModeAdrenoNew" > $PathModulConfig/GpuBooster.txt ; 
        GetModeAdrenoBefore=$GetModeAdrenoNew;
    fi
    if [ "$GetModeRamBefore" != "$GetModeRamNew" ];then
        echo "$GetModeRamNew" > $PathModulConfig/custom_ram_management.txt ; 
        GetModeRamBefore=$GetModeRamNew;
    fi
    if [ "$GetModeAiBefore" != "$GetModeAiNew" ];then
        echo "$GetModeAiNew" > $PathModulConfigAi/ai_status.txt ; 
        GetModeAiBefore=$GetModeAiNew;
    fi
    echo "re run tweak . . ."
    zyc_turbo > /dev/null 2>&1
    if [ "$GetModeAiNew" == "1" ];then
        echo "turn on ai"
        zyc_auto > /dev/null 2>&1
    fi
    echo "done . . . "
    Perubahan="tidak"
    echo "exit (y/n)?"
    read keluar
    if [ $keluar == "y" ];then
        exitSetting
    else
        ListMenu
    fi
}
ListMenu