#!/system/bin/sh
# ni sh buat ganti mode paling cepet di dunia AWKWKWKWK
echo 'preparing . . .'
if [ "$(id -u)" -gt "0" ] && [ "$(whoami)" != "root" ]; then
    echo $merahHitam"please type 'su' first -_-"$ResetWarna
    echo ""
    echo "Exit after :"
    for timeExit in "3s 2s 1s 0s" ;
    do
        echo "$timeExit"
        sleep 1s
    done
    exit -1
fi
if [ ! -e /data/mod_path.txt ]; then
    zyc_turbo
fi
ModPath=$(cat /data/mod_path.txt)
Path=$ModPath/modul_mantul/ZyC_mod
PathModulConfig=$Path/ZyC_Turbo_config
if [ ! -z "$1" ];then
    echo "updating mode to '$1',please wait. . .";
    printf "$1" | zyc_mode > /dev/null 2>&1;
    usleep 100000
    echo "update mode to '$1' done .";
fi;
if [ ! -z "$2" ];then
    echo "updating mode render to '$2',please wait. . .";
    printf "$2" | zyc_render > /dev/null 2>&1;
    usleep 100000
    echo "update mode render to '$2' done .";
fi;
zyc_turbo > /dev/null 2>&1
mode=$(cat "$PathModulConfig/status_modul.txt");
render=$(cat "$PathModulConfig/mode_render.txt");
echo "use mode [$mode]  and render using [$render]";
echo 'request done . . .';
echo "see log at $Path/ZyC_turbo.log";
