#!/system/bin/sh
# ni sh buat ganti mode lah
echo 'wait . . .';
if [ "$(id -u)" -gt "0" ] && [ "$(whoami)" != "root" ]; then
    echo $merahHitam"please type 'su' first -_-"$ResetWarna
    echo ""
    echo "Exit after :"
    for timeExit in "3s 2s 1s 0s" ;
    do
        echo "$timeExit"
        sleep 1s
    done
    exit -1
fi
if [ ! -e /data/mod_path.txt ]; then
    zyc_turbo
fi
ModPath=$(cat /data/mod_path.txt)
Path=$ModPath/modul_mantul/ZyC_mod
PathModulConfig=$Path/ZyC_Turbo_config
echo "Change render mode script to? : ";
render=$(cat "$PathModulConfig/mode_render.txt");
echo "you use render mode [$render]";
read  modeNya
if [ -z $modeNya ];then
    echo "you still use [$render]";
else
    echo $modeNya > $PathModulConfig/mode_render.txt;
    echo "mode updated to [$modeNya]";
    zyc_turbo > /dev/null 2>&1
fi;
echo 'request done . . .';
echo "see log at $Path/ZyC_turbo.log";
