#!/system/bin/sh
# ni sh buat nge trigger ganti mode aja
echo 'wait . . .';
GetBusyBox="none"
PathBusyBox="none"
for i in /system/bin /system/xbin /sbin /su/xbin; do
    if [ "$GetBusyBox" == "none" ]; then
        if [ -f $i/busybox ]; then
            GetBusyBox=$i/busybox;
        fi;
        PathBusyBox=$i
    fi;
done;
nohup=nohup
if [ -e "$PathBusyBox/nohup" ];then
    nohup=$PathBusyBox/nohup
fi
if [ "$(id -u)" -gt "0" ] && [ "$(whoami)" != "root" ]; then
    echo $merahHitam"please type 'su' first -_-"$ResetWarna
    echo ""
    echo "Exit after :"
    for timeExit in "3s 2s 1s 0s" ;
    do
        echo "$timeExit"
        usleep 1000000
    done
    exit -1
fi
ModulPath=$(cat /system/etc/ZyC_Ai/magisk_path.txt)
sh $ModulPath/ZyC_Turbo/initialize.sh "terminal" & wait
RunStatus="kaga"
if [ ! -e $ModulPath/ZyC_Turbo/system/etc/ZyC_Ai/mod_path.txt ]; then
    $nohup ./$ModulPath/ZyC_Turbo/service.sh "Terminal" 2>/dev/null 1>/dev/nul & 
	RunStatus="iya"
fi
ModPath=$(cat $ModulPath/ZyC_Turbo/system/etc/ZyC_Ai/mod_path.txt)
Path=$ModPath/modul_mantul/ZyC_mod
PathModulConfig=$Path/ZyC_Turbo_config
if [ $RunStatus == "kaga" ];then
	$nohup ./$ModulPath/ZyC_Turbo/service.sh "Terminal" 2>/dev/null 1>/dev/nul & 
fi
mode=$(cat "$PathModulConfig/status_modul.txt");
render=$(cat "$PathModulConfig/mode_render.txt");
echo "use mode [$mode]  and render using [$render]";
echo "see log at $Path/ZyC_turbo.log";
echo 'request done . . .';
